urls.py
from django.conf.urls import url, include

from . import views

app_name = 'nodectl'
urlpatterns = [
    # ex: /nodectl/
    url(r'^$', views.index, name='index'),
    # ex /nodectl/node/2
    url(r'^node/(?P<node_id>[0-9]+)$', views.node, name='node'),
    # ex /nodectl/nodedevice/2
    url(r'^nodedevice/(?P<nodedevice_id>[0-9]+)$', views.nodedevice, name='nodedevice'),
    # ex /nodectl/nodedeviceset/2
    url(r'^nodedeviceset/(?P<ndDetail_id>[0-9]+)$', views.nodedeviceset, name='nodedeviceset'),

]

models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Class_type(models.Model):
  descr        = models.CharField(max_length=200)

  def __str__(self):
    return self.descr


class Node(models.Model):
  descr        = models.CharField(max_length=200)
  first_active = models.DateTimeField('Date first seen active')
  last_active  = models.DateTimeField('Date and time of last activity')
  node         = models.IntegerField()
  mqtt_topic   = models.CharField(max_length=100)
  last_status  = models.CharField(max_length=200)

  def __str__(self):
    return self.descr

  
class Device(models.Model):
  name         = models.CharField(max_length=30)
  device_id    = models.IntegerField(default=0)
  descr        = models.CharField(max_length=200)
  class_id     = models.ForeignKey(Class_type)
  info_float1  = models.CharField(max_length=30)
  info_float2  = models.CharField(max_length=30)
  info_float3  = models.CharField(max_length=30)
  info_float4  = models.CharField(max_length=30)

  def __str__(self):
    return self.name

  
class NodeDevice(models.Model):
  node_id      = models.ForeignKey(Node)
  device_id    = models.ForeignKey(Device)
  instance     = models.IntegerField()
  last_status  = models.CharField(max_length=200)
  
  def __str__(self):
    #node = Node.objects.get(id=1)
    return '{} - {}'.format(self.node_id.descr, self.device_id.name)
    
  def mqtt_topic(self):
    return("{}/{}/{}".format(self.node_id.mqtt_topic, \
      self.device_id.name, self.instance))
    
class ndDetail(models.Model):
  nd_id          = models.ForeignKey(NodeDevice)
  detail_type    = models.CharField(max_length=1)
  detail_posn    = models.IntegerField(default=1)
  detail_text    = models.CharField(max_length=30)
  detail_descr   = models.CharField(max_length=200)
  req_value      = models.FloatField(help_text="This value will be sent to the target node as a parameter update")
  reported_value = models.FloatField()
  last_update    = models.DateTimeField()
  min_value      = models.FloatField(null=True)
  max_value      = models.FloatField(null=True)
  
  def __str__(self):
    return "{} - {} - {} - {}".format(self.nd_id.node_id.descr, self.nd_id.device_id.name,\
      self.detail_type, self.detail_text)
    
class RadioMsg(models.Model):
  ID       = models.IntegerField(primary_key=True)
  dt       = models.DateTimeField()
  nodeID   = models.IntegerField()
  deviceID = models.IntegerField()
  instance = models.IntegerField()
  action   = models.CharField(max_length=1)
  result   = models.IntegerField()
  float_1  = models.FloatField()
  float_2  = models.FloatField()
  float_3  = models.FloatField()
  float_4  = models.FloatField()
  tx_rx    = models.CharField(max_length=1)
  RSSI     = models.FloatField()
  req_id   = models.BigIntegerField()
  
  class Meta:
    db_table = "radio_msg"
    managed=False
    

forms.py
from django import forms
from .models import ndDetail

class NodeDeviceSetForm(forms.ModelForm):
  class Meta:
    model = ndDetail
    fields = ['req_value']
  
  

views.py
from django.shortcuts import render, HttpResponse, get_object_or_404
from django.template import loader, Context
from .models import Node, NodeDevice, RadioMsg, ndDetail
from .forms import NodeDeviceSetForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from django import forms
import paho.mqtt.client as mqtt
import paho.mqtt.publish as publish
import json
  
global mqttlist

# Create your views here.

# ********************************************************************
def index(request):
  """ This provides the data for the initial index screen
  """
  node_list = Node.objects.all()
  context = {'node_list': node_list}
  return render(request, 'nodectl/index.html', context)

# ********************************************************************    
def node(request, node_id):
  node = get_object_or_404(Node, pk=node_id)
  node_devices = NodeDevice.objects.all().filter(node_id = node.id)
  cSql = "SELECT * from radio_msg WHERE nodeID = {} ORDER BY dt \
      DESC LIMIT 1".format(node.node)
  r = RadioMsg.objects.raw(cSql)
  if r[0] is not None:
    node.last_status = r[0].dt
    node.save()

  return render(request, 'nodectl/node.html', {'node': node, 'nodedevices': node_devices})
  
def on_mqtt_message(client, userdata, msg):
  """This procedure is called each time a mqtt message is received"""
  mqttlist.append(msg.payload)
  print('got a message')

# ********************************************************************
def on_mqtt_connect(client, userdata, flags, rc):
    """This procedure is called on connection to the mqtt broker"""
    client.subscribe("house/#")
    
  

def nodedevice(request, nodedevice_id):
  """
  """

  mqttlist = list()
  client = mqtt.Client()
  client.on_connect = on_mqtt_connect
  client.on_message = on_mqtt_message
  client.connect("127.0.0.1", 1883, 60)
  #client.subscribe("house/#")
  client.loop(timeout=1.0)

  # get the nodedevice object
  nodedevice = get_object_or_404(NodeDevice, pk=nodedevice_id)
  c = Context({'nodedevice': nodedevice})
  c['mqtt_topic'] = nodedevice.mqtt_topic()
  
  # get any info details for the nd
  ndInfo = ndDetail.objects.filter(nd_id=nodedevice_id).filter(detail_type = 'I')
  c['ndInfo'] = ndInfo
  
  # get any param details for the nd
  ndParam = ndDetail.objects.filter(nd_id=nodedevice_id).filter(detail_type = 'P')
  for p in ndParam:
    cSql = "SELECT * from radio_msg WHERE nodeID = {} AND deviceID = {} AND instance = {} \
        AND action = 'R' ORDER BY dt DESC LIMIT 1".format(nodedevice.node_id.node, \
        nodedevice.device_id.device_id, nodedevice.instance)
    r = RadioMsg.objects.raw(cSql)
    for r1 in r:
    #if r is not None:
      if p.detail_posn == 1:
        p.reported_value = r1.float_1
      elif p.detail_posn == 2:
        p.reported_value = r1.float_2
      break
    #p.save()
  
  
  c['ndParam'] = ndParam
  
  c['mqtt'] = mqttlist  
  
  # get last radio messages 
  sql = "SELECT * from radio_msg WHERE nodeID = {} AND deviceID = {} ORDER BY dt DESC \
      LIMIT 15".format(nodedevice.node_id.node, nodedevice.device_id.device_id)
  c['sql'] =sql
  radio_list = RadioMsg.objects.raw(sql)
  
  c['radiolist'] = radio_list
  client.disconnect()
  return render(request, 'nodectl/nodedevice.html', c)
  
# ********************************************************************
def nodedeviceset(request, ndDetail_id):
  ndParam = ndDetail.objects.get(id=ndDetail_id)
  jErrorMsg = ''
 
  client = mqtt.Client()
  #client.on_connect = on_mqtt_connect
  #client.on_message = on_mqtt_message
  client.connect("127.0.0.1", 1883, 60)

  if request.method == 'POST':
    form = NodeDeviceSetForm(request.POST, instance = ndParam)
  
    if form.is_valid():
      if form.cleaned_data['req_value'] < ndParam.min_value:
        jErrorMsg = "Parameter cannot be less than {}".format(ndParam.min_value)
      elif form.cleaned_data['req_value'] > ndParam.max_value:
        jErrorMsg = "Parameter cannot be more than {}".format(ndParam.max_value)
      else:
        form.save()
        topic = "{}/P".format(ndParam.nd_id.mqtt_topic())
        payload = json.dumps({ndParam.detail_text: form.cleaned_data['req_value']})
        print(ndParam.nd_id.mqtt_topic())
        publish.single(topic, payload)
        client.disconnect() 
        return HttpResponseRedirect(reverse('nodectl:nodedevice', \
          args=(ndParam.nd_id.id,)))
      form.req_value.error = jErrorMsg
  else:
    form = NodeDeviceSetForm()
 
  c = Context({'form': form})
  c['ndDetail'] = ndParam
  c['error_message'] = jErrorMsg
  
  c['explain'] = "{}  Minimum value is {}, max value is {}".format(ndParam.detail_descr,\
    ndParam.min_value, ndParam.max_value)
  client.disconnect() 
  return render(request, 'nodectl/nodedeviceset.html', c)

templates/nodectl/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="/static/nodectl/css/style.css">
    <title>{% block title %}Node Control{% endblock %}</title>
</head>

<body>
<H1>Node control system</H1>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

templates/nodectl/index.html
{% extends "nodectl/base.html" %}

{% block content %}
<h1>{{ user }}</h1>
{% if node_list %}
    <ul>
    {% for node in node_list %}
        <li><a href="{% url 'nodectl:node' node.id %}">{{ node.descr }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No nodes are available.</p>
{% endif %}
{% endblock %}

templates/nodectl/node.html
{% extends "nodectl/base.html" %}

{% block content %}
<h1>{{ node.descr }}</h1>
<div class="w3-row">
  <div class="w3-col s2">
    <p>Description</p> 
  </div>
    <div class="w3-col s10">
    <p>{{ node.descr }}</p> 
  </div>
</div>
<div class="w3-row">
  <div class="w3-col s2">
    <p>mqtt topic</p> 
  </div>
    <div class="w3-col s10">
    <p>{{ node.mqtt_topic }}</p> 
  </div>
</div><div class="w3-row">
  <div class="w3-col s2">
    <p>first active</p> 
  </div>
    <div class="w3-col s10">
    <p>{{ node.first_active }}</p> 
  </div>
</div><div class="w3-row">
  <div class="w3-col s2">
    <p>Last active</p> 
  </div>
    <div class="w3-col s10">
    <p>{{ node.last_active }}</p> 
  </div>
</div><div class="w3-row">
  <div class="w3-col s2">
    <p>Last status</p> 
  </div>
    <div class="w3-col s10">
    <p>{{ node.last_status }}</p> 
  </div>
</div>

{% if nodedevices %}
    <ul>
    {% for device in nodedevices %}
        <li><a href="{% url 'nodectl:nodedevice' device.id %}">{{ device }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No devices defined are available.</p>
{% endif %}

{% endblock %}

templates/nodectl/nodedevice.html
{% extends "nodectl/base.html" %}

{% block content %}
<h1>{{ nodedevice }}</h1>
<p>Node ID {{ nodedevice.node_id.node }} {{ nodedevice.node_id.descr }}</p>
<p>Device ID {{ nodedevice.device_id.device_id }} {{ nodedevice.device_id.descr }}</p>
<p>Mqqt topic {{ mqtt_topic }}</p>
{% if ndParam %}
  <h3>Parameters</h3>
  {% for det in ndParam %}
    <p><a href="{% url 'nodectl:nodedeviceset' det.id %}">{{ det }}</a></p>
    <p>{{ det.detail_text }}</p>
    <p>Requested value: {{ det.req_value }}</p>
    <p>Reported value: {{ det.reported_value }}</p>
    <p> </p>

  {% endfor %}
{% else %}
    <p>No parameter records are available.</p>
{% endif %}

{% if ndInfo %}
  <h3>Last info</h3>
  {% for det in ndInfo %}
    <p>{{ det }}</p>
  {% endfor %}
{% else %}
    <p>No parameter records are available.</p>
{% endif %}

{% if mqttlist %}
  <h3>mqtt info</h3>
  {% for m in mqttlist %}
    <p>{{ m }}</p>
  {% endfor %}
{% else %}
    <p>No MQTT data are available.</p>
{% endif %}



<P>SQL {{ sql }}</P>
{% if radiolist %}
    <table class="w3-table-all w3-hoverable">
      <thead>
        <tr class="w3-light-grey">
          <th>Action</th>
          <th>Result</th>
          <th>Float 1</th>
          <th>Float 2</th>
          <th>Float 3</th>
          <th>Float 4</th>
          <th>Tx Rx</th>
          <th>RSSI</th>
          <th>Date/time</th>
        </tr>
      </thead>
    {% for radio in radiolist %}
      <tr>
        <td>{{ radio.action }}</td>
        <td>{{ radio.result }}</td>
        <td>{{ radio.float_1 }}</td>
        <td>{{ radio.float_2 }}</td>
        <td>{{ radio.float_3 }}</td>
        <td>{{ radio.float_4 }}</td>
        <td>{{ radio.tx_rx }}</td>
        <td>{{ radio.RSSI }}</td>
        <td>{{ radio.dt }}</td>
      </tr>
    {% endfor %}
    </table>
{% else %}
    <p>No radio messages are available.</p>
{% endif %}


{% endblock %}

templates/nodectl/nodedeviceset.html
{% extends "nodectl/base.html" %}

{% block content %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'nodectl:nodedeviceset' ndDetail.id %}" method="post">
{% csrf_token %}
{{ form }}
<input type="submit" value="Change" />
</form>
<p>{{ explain }}</p>
{% endblock %}